version: "3.9"
services:
  pgsql:
    platform: linux/amd64
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${PGSQL_USER}"
      POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
      # POSTGRES_HOST_AUTH_METHOD: "all"
      TZ: Asia/Jakarta
    ports:
      - "25432:5432"
    volumes:
      - ./xdata:/var/lib/postgresql
    networks:
      - dba

networks:
  dba:
